github:
  description: "Apache Sling Maven Enforcer Rules"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
